### ISSUE TITLE
Add spacing for docs function

### ISSUE THREAD

**Issue by DleanJeans** [CraftSpider/dpytest#59]
Right now it's suffocating

![image](https://user-images.githubusercontent.com/12462089/123213371-213fc900-d4f0-11eb-8320-feb957bd166a.png)

Maybe something like
```css
.py.function {
    margin-bottom: 50px;
}

.py.method {
    margin-bottom: 30px;
}
```

![image](https://user-images.githubusercontent.com/12462089/123213412-2c92f480-d4f0-11eb-925b-60a3bc8866d1.png)
